Common:
  # Name of relic when receiving the relic
  Name: "&bCommon Relic"
  # Item Lore
  Lore: "&bPlace the relic to claim!"
  # Messages to run
  Message:
    Receive: "You found a Common relic"
    Opening: "Opening Common relic"
  Commands:
  - "give {PLAYER} diamond_block 3"
Epic:
  # Name of relic when receiving the relic
  Name: "&bEpic Relic"
  # Item Lore
  Lore: "&bPlace the relic to claim!"
  # Messages to run
  Message:
    Receive: "You found a Epic relic"
    Opening: "Opening Epic relic"
  Commands:
  - "give {PLAYER} diamond_block 5"
Rare:
  # Name of relic when receiving the relic
  Name: "&l&cRare Relic"
  # Item Lore
  Lore: "&bPlace the relic to claim!"
  Message:
    Receive: "You found a Rare relic"
    Opening: "Opening Rare relic"
  Commands:
  - "give {PLAYER} diamond_block 10"
Legendary:
  # Name of relic when receiving the relic
  Name: "&6Legendary Relic"
  # Item Lore
  Lore: "&bPlace the relic to claim!"
  # Messages to run
  Message:
    Receive: "You found a Legendary relic"
    Opening: "Opening Legendary relic"
  Commands:
  - "give {PLAYER} diamond_block 32"
Mythical:
  #  Name of relic when receiving the relic
  Name: "&fMythical Relic"
  # Item Lore
  Lore: "&bPlace the relic to claim!"
  # Messages to run
  Message:
    Receive: "You found a Mythical relic"
    Opening: "Opening Mythical relic"
  Commands:
  - "give {PLAYER} diamond_block 64"
